version: '3.4'

services:
  namesweb:
    image: namesweb
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
     # - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_URLS=http://+:80
     # - ASPNETCORE_HTTPS_PORT=44348
    ports:
      - "57270:80"
     # - "44348:443"
